DELETE  http://localhost:3003/api/sharedcalendar/63932edaaa0f532257bd1df0
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaGFyZWRDYWxlbmRhcklEIjoiNjM5MzJlZGFhYTBmNTMyMjU3YmQxZGYwIiwiaWF0IjoxNjcwNTk1MzU0fQ.Bonsk3tLKnWb0wPsjJ29IjcMo8139ENiKLgIwqXC01A