GET http://localhost:3003/api/sharedcalendar/636e3640b61822f643abdd8f
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaGFyZWRDYWxlbmRhcklEIjoiNjM2ZTM2NDBiNjE4MjJmNjQzYWJkZDhmIiwiaWF0IjoxNjY4MTgwMTcxfQ.ZFg_QAZIW5Xm4Ylk-MbtlueutvdYWA4g_XzAyl81NFA