GET http://localhost:3003/api/sharedcalendar/638b22ed6d579fc7e61f7bf9
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaGFyZWRDYWxlbmRhcklEIjoiNjM4YjIyZWQ2ZDU3OWZjN2U2MWY3YmY5IiwiaWF0IjoxNjcwMjQ5ODYyfQ.hXdr_LRZAMkLwOP6h8GfE8EkOXLJuYQxg0aMoKqiDvA