GET http://localhost:3003/api/sharedcalendar/636507f2a9910a34c960565f
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaGFyZWRDYWxlbmRhcklEIjoiNjM2NTA3ZjJhOTkxMGEzNGM5NjA1NjVmIiwiaWF0IjoxNjY3NjQ2MTYwfQ.LHfGorngZoGhhISDtKMGbrjiiZWDKrfZU5q7m5UR5HQ