POST http://localhost:3003/api/privatecalendar
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaGFyZWRDYWxlbmRhcklEIjoiNjM3YTA1YjEwYTdhY2Y1ODE2ZWQ0Yzk2IiwiaWF0IjoxNjY4OTQxMjU4fQ.y7FdKkzvwHIjuJwrCRpo56NuL71tjVJIHHC5cupaJzs

{
    "sharedCalendarID": "636e3640b61822f643abdd8f",
    "name": "thisiz testii",
    "events": [
        {
        "start": "2023-03-07T10:30:00",
        "duration": "PT1H45M",
        "timeZone": "jotain"
      },
      {
        "start": "2023-03-08T09:30:00",
        "duration": "PT1H45M",
        "timeZone": "jotain"
      },
      {
        "start": "2023-03-08T12:00:00",
        "duration": "PT1H45M",
        "timeZone": "jotain"
      },
      {
        "start": "2023-03-06T11:30:00",
        "duration": "PT1H45M",
        "timeZone": "jotain"
      }
    ]
}